name: Run tests on any Push event

on:
  push:
    branches:
      - '*'
jobs:
  run_tests:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r requirements.txt